apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1800"
spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.21
    helm:
      releaseName: argo-events
      valuesObject:
        crds:
          install: true
          keep: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
