apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submit-workflows
  namespace: ml-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-submit-workflows
  namespace: ml-workflows
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
roleRef:
  kind: Role
  name: submit-workflows
  apiGroup: rbac.authorization.k8s.io
